### ISSUE TITLE
Problem installing, unable to resolve minidown dependency

### ISSUE THREAD

**Issue by privatecoder** [Nix-wie-weg/dasheets#3]
I'm unable to install dasheets in osx yosemite as it depends on minidown ~> 1.0.0 but only 2.1.1 can be find in the repo, plz update.
![screen shot 2015-03-25 at 11 45 33 pm](https://cloud.githubusercontent.com/assets/1447123/6841523/26a95762-d349-11e4-9f28-0101c63b45fe.png)

**Comment by der-flo** [comment]
I've released version 0.0.7 to rubygems.org.
